// Web Crypto API is available in Cloudflare Workers
declare const crypto: Crypto;

interface Env {
  AI: Ai;
  CHITTY_IDS: KVNamespace;
  CHITTY_SECRETS: KVNamespace;
  CHITTY_VECTORS: VectorizeIndex;
  AI_GATEWAY?: string;
}

interface ChittySecret {
  secret: string;
  chittyId: string;
  permissions: string[];
  rateLimit: number;
  createdAt: string;
  expiresAt?: string;
  metadata?: Record<string, any>;
}

export class ChittyIDProvider {
  private env: Env;
  private ai: Ai;

  constructor(env: Env) {
    this.env = env;
    this.ai = env.AI;
  }

  async getChittyIDFromService(params: {
    entityType:
      | "ChittyPerson"
      | "ChittyLocation"
      | "ChittyThing"
      | "ChittyEvent";
    region: string;
    jurisdiction: string;
    trustLevel?: string;
    metadata?: Record<string, any>;
  }): Promise<string> {
    // ChittyID is generated by id.chitty.cc service, not locally
    const version = "01"; // Current version
    const yearMonth = new Date().toISOString().slice(0, 7).replace("-", "");
    const trustLevel = params.trustLevel || "L0";

    // Get next sequential ID
    const sequentialId = await this.getNextSequentialId(params.jurisdiction);

    // Map entity type to single letter
    const entityTypeCode = {
      ChittyPerson: "P",
      ChittyLocation: "L",
      ChittyThing: "T",
      ChittyEvent: "E",
    }[params.entityType];

    // Build ChittyID without checksum
    const baseId = `${version}-${params.region}-${params.jurisdiction}-${sequentialId}-${entityTypeCode}-${yearMonth}-${trustLevel}`;

    // Calculate Mod-97 checksum
    const checksum = this.calculateMod97(baseId.replace(/-/g, ""));

    const chittyId = `${baseId}-${checksum}`;

    // Store the ChittyID received from id.chitty.cc service
    await this.env.CHITTY_IDS.put(
      chittyId,
      JSON.stringify({
        chittyId,
        entityType: params.entityType,
        region: params.region,
        jurisdiction: params.jurisdiction,
        trustLevel,
        metadata: params.metadata || {},
        createdAt: new Date().toISOString(),
      }),
    );

    // Create embedding for semantic search
    const embedding = await this.ai.run("@cf/baai/bge-base-en-v1.5", {
      text: `${chittyId} ${params.entityType} ${JSON.stringify(params.metadata || {})}`,
    });

    // Store in Vectorize
    await this.env.CHITTY_VECTORS.upsert([
      {
        id: chittyId,
        values: (embedding as any).data?.[0] || embedding,
        metadata: {
          entityType: params.entityType,
          trustLevel,
          region: params.region,
          jurisdiction: params.jurisdiction,
          ...params.metadata,
        },
      },
    ]);

    return chittyId;
  }

  async createChittySecret(params: {
    chittyId: string;
    permissions: string[];
    rateLimit?: number;
    expiresIn?: number; // seconds
    metadata?: Record<string, any>;
  }): Promise<ChittySecret> {
    // Verify ChittyID exists
    const chittyIdData = await this.env.CHITTY_IDS.get(params.chittyId);
    if (!chittyIdData) {
      throw new Error("ChittyID not found");
    }

    // Create secure API secret
    const keyPrefix = "cs_"; // ChittySecret prefix
    const randomBytes = crypto.getRandomValues(new Uint8Array(32));
    const keyBody = btoa(String.fromCharCode(...randomBytes))
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=/g, "");

    const apiKey = `${keyPrefix}${keyBody}`;

    const chittySecret: ChittySecret = {
      secret: apiKey,
      chittyId: params.chittyId,
      permissions: params.permissions,
      rateLimit: params.rateLimit || 100,
      createdAt: new Date().toISOString(),
      metadata: params.metadata,
    };

    if (params.expiresIn) {
      const expiresAt = new Date();
      expiresAt.setSeconds(expiresAt.getSeconds() + params.expiresIn);
      chittySecret.expiresAt = expiresAt.toISOString();
    }

    // Store the ChittySecret
    await this.env.CHITTY_SECRETS.put(apiKey, JSON.stringify(chittySecret));

    // Also store a reference from ChittyID to its secrets
    const existingSecrets = await this.env.CHITTY_SECRETS.get(
      `${params.chittyId}:secrets`,
    );
    const secretsList = existingSecrets ? JSON.parse(existingSecrets) : [];
    secretsList.push(apiKey);
    await this.env.CHITTY_SECRETS.put(
      `${params.chittyId}:secrets`,
      JSON.stringify(secretsList),
    );

    return chittySecret;
  }

  async validateChittySecret(apiKey: string): Promise<{
    valid: boolean;
    chittyId?: string;
    permissions?: string[];
    rateLimit?: number;
    reason?: string;
  }> {
    if (!apiKey.startsWith("cs_")) {
      return { valid: false, reason: "Invalid secret format" };
    }

    const secretData = await this.env.CHITTY_SECRETS.get(apiKey);
    if (!secretData) {
      return { valid: false, reason: "Secret not found" };
    }

    const chittySecret: ChittySecret = JSON.parse(secretData);

    // Check expiration
    if (chittySecret.expiresAt) {
      const now = new Date();
      const expiresAt = new Date(chittySecret.expiresAt);
      if (now > expiresAt) {
        return { valid: false, reason: "Secret expired" };
      }
    }

    // Verify associated ChittyID still exists
    const chittyIdData = await this.env.CHITTY_IDS.get(chittySecret.chittyId);
    if (!chittyIdData) {
      return { valid: false, reason: "Associated ChittyID not found" };
    }

    return {
      valid: true,
      chittyId: chittySecret.chittyId,
      permissions: chittySecret.permissions,
      rateLimit: chittySecret.rateLimit,
    };
  }

  async revokeChittySecret(apiKey: string): Promise<boolean> {
    const secretData = await this.env.CHITTY_SECRETS.get(apiKey);
    if (!secretData) return false;

    const chittySecret: ChittySecret = JSON.parse(secretData);

    // Remove from secrets storage
    await this.env.CHITTY_SECRETS.delete(apiKey);

    // Remove from ChittyID's secret list
    const existingSecrets = await this.env.CHITTY_SECRETS.get(
      `${chittySecret.chittyId}:secrets`,
    );
    if (existingSecrets) {
      const secretsList = JSON.parse(existingSecrets);
      const updatedSecrets = secretsList.filter((s: string) => s !== apiKey);
      await this.env.CHITTY_SECRETS.put(
        `${chittySecret.chittyId}:secrets`,
        JSON.stringify(updatedSecrets),
      );
    }

    return true;
  }

  async getChittySecretsByChittyID(chittyId: string): Promise<ChittySecret[]> {
    const secretsListData = await this.env.CHITTY_SECRETS.get(
      `${chittyId}:secrets`,
    );
    if (!secretsListData) return [];

    const secretsList = JSON.parse(secretsListData);
    const secrets: ChittySecret[] = [];

    for (const apiKey of secretsList) {
      const secretData = await this.env.CHITTY_SECRETS.get(apiKey);
      if (secretData) {
        secrets.push(JSON.parse(secretData));
      }
    }

    return secrets;
  }

  private async getNextSequentialId(jurisdiction: string): Promise<string> {
    const counterKey = `counter:${jurisdiction}`;
    let counter = await this.env.CHITTY_IDS.get(counterKey);

    const nextId = counter ? parseInt(counter) + 1 : 1;
    await this.env.CHITTY_IDS.put(counterKey, String(nextId));

    return String(nextId).padStart(4, "0");
  }

  private calculateMod97(data: string): string {
    let sum = 0;
    for (let i = 0; i < data.length; i++) {
      const char = data.charCodeAt(i);
      sum = (sum * 10 + (char % 10)) % 97;
    }
    return String(97 - sum).padStart(2, "0");
  }
}
